# Generated by Django 3.1.7 on 2021-04-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='c_password',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
